# Use postgres/asdf1234 user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: asdf1234
